### ISSUE TITLE
File format extension

### ISSUE THREAD

**Issue by rleduc42** [topdownproteomics/proteoform-nomenclature-standard#17] opened 2017-07-24 14:30 UTC
Greg Blakney at the Mag Lab asked if there was a recommended file extension for a FASTA file where the sequences were formatted according to our standard. My first thought was that this is outside of our current scope--but the more I thought about it, the more I figured it might be worth considering.

Regards,

Rich

**Comment by sgibb** [comment] 2017-07-31 08:43
Duplicate of #11

**Comment by stefanks** [comment] 2017-07-31 13:48
Closing, moving discussion to https://github.com/topdownproteomics/proteoform-nomenclature-standard/issues/11

**Closed as completed by stefanks** 2017-07-31 13:48 UTC
